[package]
name = "metaflac"
version = "0.1.8"
authors = ["James Hurst <jh.jameshurst@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/jameshurst/rust-metaflac"
repository = "https://github.com/jameshurst/rust-metaflac"
documentation = "https://jameshurst.github.io/rust-metaflac"
description = "A library for reading and writing FLAC metadata."
keywords = ["flac", "audio", "parser", "metadata"]

[dependencies]
log = "0.3.7"
rustc-serialize = "0.3.23"
byteorder = "1.0.0"
num = "0.1.37"
